name: Run `go run app reload`

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:       # Allows manual triggering too

jobs:
  run-reload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3' # Change to your required Go version

      - name: Run reload
        env:
          TS_API_TOKEN: ${{ secrets.TS_API_TOKEN }}
          NEXTDNS_API_TOKEN: $${{ secrets.NEXTDNS_API_TOKEN }}
        run: |
          go run app reload
